OpenIDE-Module-Name=gprofng GUI
OpenIDE-Module-Display-Category=Tools
OpenIDE-Module-Short-Description=gprofng GUI
OpenIDE-Module-Long-Description=gprofng GUI
Actions/Analyze=Analyze
Menu/Analyze=&Analyze
Menu/Help/HelpShortcuts/org-gprofng-mpmt-help-Welcome_Analyzer.xml=gprofng GUI Help
LBL_loaderName=gprofng GUI Data Loader
LBL_Action=Analyze
CTL_Analyzing=Analyzing
CTL_AnalyzingDescription=gprofng GUI
CTL_display=gprofng GUI
CTL_displayDescription=gprofng GUI
CTL_editor=Editor Window
CTL_editorDescription=gprofng GUI Editor
CTL_explorer=Explorer
CTL_explorerDescription=gprofng GUI Explorer
CTL_properties=Properties Window
CTL_propertiesDescription=gprofng GUI Properties Window

